if type znap &>/dev/null; then
  znap source ~/.local/share/omakub-mac/defaults/zsh/rc
else
  source ~/.local/share/omakub-mac/defaults/zsh/rc
fi

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"