[env]
TERM = "xterm-256color"

# fix for integration with zellij and Macos login shell
# https://github.com/alacritty/alacritty/issues/1071
# https://github.com/zellij-org/zellij/issues/823
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach --index 0 --create"]

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
